obj-$(CONFIG_ANDROID_OLD_OPENBINDER_IPC)+= old_binderdev.o
obj-$(CONFIG_ANDROID_OPENBINDER_IPC)	+= openbinder.o
obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder.o
obj-$(CONFIG_ANDROID_LOGGER)		+= logger.o
obj-$(CONFIG_ANDROID_RAM_CONSOLE)	+= ram_console.o
obj-$(CONFIG_ANDROID_TIMED_OUTPUT)	+= timed_output.o
obj-$(CONFIG_ANDROID_TIMED_GPIO)	+= timed_gpio.o
obj-$(CONFIG_ANDROID_LOW_MEMORY_KILLER)	+= lowmemorykiller.o
obj-$(CONFIG_ANDROID_INTF_ALARM)	+= alarm.o
obj-$(CONFIG_ANDROID_INTF_ALARM_DEV)	+= alarm-dev.o
obj-$(CONFIG_ANDROID_VIBRATOR_COMPAT)	+= android-vibrator_compat.o
obj-$(CONFIG_ANDROID_POWER_COMPAT)	+= android_power_compat.o
obj-$(CONFIG_ANDROID_EZX_EAC)	+= ezx_eac.o
obj-$(CONFIG_ANDROID_BACKLIGHT_COMPAT)	+= backlight_compat.o
obj-$(CONFIG_ANDROID_EVENT0_COMPAT)	+= event0_compat.o

old_binderdev-objs := old_iobuffer.o old_binder.o old_binder_node.o old_binder_proc.o old_binder_thread.o old_binder_transaction.o
